#!/bin/bash
export REALM_NAME
export DISPLAY=:0
export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
export XDG_RUNTIME_DIR=/run/user/1000
export PULSE_SERVER=unix:/run/user/host/pulse/native
export GNOME_DESKTOP_SESSION_ID=this-is-deprecated
export NO_AT_BRIDGE=1
exec "$@"
